#
# Image for running test suite.
#
FROM node:6

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app

RUN npm install
ENV NODE_ENV=production

# Bundle app source
COPY . .

EXPOSE 3000
CMD ["npm", "test"]
